#ifndef CONFIG_LISA_L_1_0_H
#define CONFIG_LISA_L_1_0_H

#define BOARD_LISA_L

/* Lisa/L has an 8MHZ external clock and 72MHz internal. */
#define EXT_CLK 8000000
#define AHB_CLK 72000000


/* SPI slave mapping */


#define SPI_SELECT_SLAVE1_PORT GPIOA
#define SPI_SELECT_SLAVE1_PIN GPIO4

#define SPI_SELECT_SLAVE2_PORT GPIOB
#define SPI_SELECT_SLAVE2_PIN GPIO12




/*
 * I2C
 *
 */
#define I2C1_GPIO_PORT GPIOB
#define I2C1_GPIO_SCL GPIO6
#define I2C1_GPIO_SDA GPIO7

#define I2C2_GPIO_PORT GPIOB
#define I2C2_GPIO_SCL GPIO10
#define I2C2_GPIO_SDA GPIO11


/*
 * UART pin configuration
 *
 * sets on which pins the UARTs are connected
 */
#define UART1_GPIO_AF 0
#define UART1_GPIO_PORT_RX GPIO_BANK_USART1_RX
#define UART1_GPIO_RX GPIO_USART1_RX
#define UART1_GPIO_PORT_TX GPIO_BANK_USART1_TX
#define UART1_GPIO_TX GPIO_USART1_TX

#define UART2_GPIO_AF 0
#define UART2_GPIO_PORT_RX GPIO_BANK_USART2_RX
#define UART2_GPIO_RX GPIO_USART2_RX
#define UART2_GPIO_PORT_TX GPIO_BANK_USART2_TX
#define UART2_GPIO_TX GPIO_USART2_TX

#define UART3_GPIO_AF AFIO_MAPR_USART3_REMAP_PARTIAL_REMAP
#define UART3_GPIO_PORT_RX GPIO_BANK_USART3_PR_RX
#define UART3_GPIO_RX GPIO_USART3_PR_RX
#define UART3_GPIO_PORT_TX GPIO_BANK_USART3_PR_TX
#define UART3_GPIO_TX GPIO_USART3_PR_TX

#define UART5_GPIO_AF 0
#define UART5_GPIO_PORT_RX GPIO_BANK_UART5_RX
#define UART5_GPIO_RX GPIO_UART5_RX
#define UART5_GPIO_PORT_TX GPIO_BANK_UART5_TX
#define UART5_GPIO_TX GPIO_UART5_TX




/*
 * PPM input
 */
#define USE_PPM_TIM2 1
#define PPM_CHANNEL         TIM_IC2
#define PPM_TIMER_INPUT     TIM_IC_IN_TI2
#define PPM_IRQ             NVIC_TIM2_IRQ
// Capture/Compare InteruptEnable and InterruptFlag
#define PPM_CC_IE           TIM_DIER_CC2IE
#define PPM_CC_IF           TIM_SR_CC2IF
#define PPM_GPIO_PORT       GPIOA
#define PPM_GPIO_PIN        GPIO1
#define PPM_GPIO_AF         0



/* PWM led  */
#define USE_PWM_LED 1
#define PWM_LED_GPIO GPIOC
#define PWM_LED_PIN GPIO13
#define PWM_LED_ON() gpio_clear(PWM_LED_GPIO,PWM_LED_PIN)
#define PWM_LED_OFF() gpio_set(PWM_LED_GPIO,PWM_LED_PIN)
#define PWM_LED_TOGGLE() gpio_toggle(PWM_LED_GPIO,PWM_LED_PIN)


/* Default actuators driver */
#define DEFAULT_ACTUATORS "subsystems/actuators/actuators_pwm.h"
#define ActuatorDefaultSet(_x,_y) ActuatorPwmSet(_x,_y)
#define ActuatorsDefaultInit() ActuatorsPwmInit()
#define ActuatorsDefaultCommit() ActuatorsPwmCommit()

/*
 * PWM
 *
 */
#define PWM_USE_TIM3 1
#define PWM_USE_TIM4 1
#define PWM_USE_TIM2 1
#define PWM_USE_TIM5 1

//tim3
#define USE_PWM1 1
#define USE_PWM2 1
#define USE_PWM3 1
#define USE_PWM4 1
//tim4
#define USE_PWM5 1
#define USE_PWM6 1
#define USE_PWM7 1
#define USE_PWM8 1
//tim2
#define USE_PWM9 1
#define USE_PWM10 1
#define USE_PWM11 1
#define USE_PWM12 1
//tim5
#define USE_PWM13 1
#define USE_PWM14 1
#define USE_PWM15 1
#define USE_PWM16 1

#define ACTUATORS_PWM_NB 16

// PWM_SERVO_x is the index of the servo in the actuators_pwm_values array
#if USE_PWM1
#define PWM_SERVO_1 0
#define PWM_SERVO_1_TIMER TIM3
#define PWM_SERVO_1_GPIO GPIO_BANK_TIM3_FR_CH1
#define PWM_SERVO_1_PIN GPIO_TIM3_FR_CH1
#define PWM_SERVO_1_AF AFIO_MAPR_TIM3_REMAP_FULL_REMAP
#define PWM_SERVO_1_OC TIM_OC1
#define PWM_SERVO_1_OC_BIT (1<<0)
#else
#define PWM_SERVO_1_OC_BIT 0
#endif

#if USE_PWM2
#define PWM_SERVO_2 1
#define PWM_SERVO_2_TIMER TIM3
#define PWM_SERVO_2_GPIO GPIO_BANK_TIM3_FR_CH2
#define PWM_SERVO_2_PIN GPIO_TIM3_FR_CH2
#define PWM_SERVO_2_AF AFIO_MAPR_TIM3_REMAP_FULL_REMAP
#define PWM_SERVO_2_OC TIM_OC2
#define PWM_SERVO_2_OC_BIT (1<<1)
#else
#define PWM_SERVO_2_OC_BIT 0
#endif

#if USE_PWM3
#define PWM_SERVO_3 2
#define PWM_SERVO_3_TIMER TIM3
#define PWM_SERVO_3_GPIO GPIO_BANK_TIM3_FR_CH3
#define PWM_SERVO_3_PIN GPIO_TIM3_FR_CH3
#define PWM_SERVO_3_AF AFIO_MAPR_TIM3_REMAP_FULL_REMAP
#define PWM_SERVO_3_OC TIM_OC3
#define PWM_SERVO_3_OC_BIT (1<<2)
#else
#define PWM_SERVO_3_OC_BIT 0
#endif

#if USE_PWM4
#define PWM_SERVO_4 3
#define PWM_SERVO_4_TIMER TIM3
#define PWM_SERVO_4_GPIO GPIO_BANK_TIM3_FR_CH4
#define PWM_SERVO_4_PIN GPIO_TIM3_FR_CH4
#define PWM_SERVO_4_AF AFIO_MAPR_TIM3_REMAP_FULL_REMAP
#define PWM_SERVO_4_OC TIM_OC4
#define PWM_SERVO_4_OC_BIT (1<<3)
#else
#define PWM_SERVO_4_OC_BIT 0
#endif



#if USE_PWM5
#define PWM_SERVO_5 4
#define PWM_SERVO_5_TIMER TIM4
#define PWM_SERVO_5_GPIO GPIO_BANK_TIM4_CH1
#define PWM_SERVO_5_PIN GPIO_TIM4_CH1
#define PWM_SERVO_5_AF 0
#define PWM_SERVO_5_OC TIM_OC1
#define PWM_SERVO_5_OC_BIT (1<<0)
#else
#define PWM_SERVO_5_OC_BIT 0
#endif

#if USE_PWM6
#define PWM_SERVO_6 5
#define PWM_SERVO_6_TIMER TIM4
#define PWM_SERVO_6_GPIO GPIO_BANK_TIM4_CH2
#define PWM_SERVO_6_PIN GPIO_TIM4_CH2
#define PWM_SERVO_6_AF 0
#define PWM_SERVO_6_OC TIM_OC2
#define PWM_SERVO_6_OC_BIT (1<<1)
#else
#define PWM_SERVO_6_OC_BIT 0
#endif

#if USE_PWM7
#define PWM_SERVO_7 6
#define PWM_SERVO_7_TIMER TIM4
#define PWM_SERVO_7_GPIO GPIO_BANK_TIM4_CH3
#define PWM_SERVO_7_PIN GPIO_TIM4_CH3
#define PWM_SERVO_7_AF 0
#define PWM_SERVO_7_OC TIM_OC3
#define PWM_SERVO_7_OC_BIT (1<<2)
#else
#define PWM_SERVO_7_OC_BIT 0
#endif

#if USE_PWM8
#define PWM_SERVO_8 7
#define PWM_SERVO_8_TIMER TIM4
#define PWM_SERVO_8_GPIO GPIO_BANK_TIM4_CH4
#define PWM_SERVO_8_PIN GPIO_TIM4_CH4
#define PWM_SERVO_8_AF 0
#define PWM_SERVO_8_OC TIM_OC4
#define PWM_SERVO_8_OC_BIT (1<<3)
#else
#define PWM_SERVO_8_OC_BIT 0
#endif



#if USE_PWM9
#define PWM_SERVO_9 8
#define PWM_SERVO_9_TIMER TIM2
#define PWM_SERVO_9_GPIO GPIO_BANK_TIM2_FR_CH1_ETR
#define PWM_SERVO_9_PIN GPIO_TIM2_FR_CH1_ETR
#define PWM_SERVO_9_AF AFIO_MAPR_TIM2_REMAP_FULL_REMAP
#define PWM_SERVO_9_OC TIM_OC1
#define PWM_SERVO_9_OC_BIT (1<<0)
#else
#define PWM_SERVO_9_OC_BIT 0
#endif

#if USE_PWM10
#define PWM_SERVO_10 9
#define PWM_SERVO_10_TIMER TIM2
#define PWM_SERVO_10_GPIO GPIO_BANK_TIM2_FR_CH234
#define PWM_SERVO_10_PIN GPIO_TIM2_FR_CH2
#define PWM_SERVO_10_AF AFIO_MAPR_TIM2_REMAP_FULL_REMAP
#define PWM_SERVO_10_OC TIM_OC2
#define PWM_SERVO_10_OC_BIT (1<<1)
#else
#define PWM_SERVO_10_OC_BIT 0
#endif

#if USE_PWM11
#define PWM_SERVO_11 10
#define PWM_SERVO_11_TIMER TIM2
#define PWM_SERVO_11_GPIO GPIO_BANK_TIM2_FR_CH234
#define PWM_SERVO_11_PIN GPIO_TIM2_FR_CH3
#define PWM_SERVO_11_AF AFIO_MAPR_TIM2_REMAP_FULL_REMAP
#define PWM_SERVO_11_OC TIM_OC3
#define PWM_SERVO_11_OC_BIT (1<<2)
#else
#define PWM_SERVO_11_OC_BIT 0
#endif

#if USE_PWM12
#define PWM_SERVO_12 11
#define PWM_SERVO_12_TIMER TIM2
#define PWM_SERVO_12_GPIO GPIO_BANK_TIM2_FR_CH234
#define PWM_SERVO_12_PIN GPIO_TIM2_FR_CH4
#define PWM_SERVO_12_AF AFIO_MAPR_TIM2_REMAP_FULL_REMAP
#define PWM_SERVO_12_OC TIM_OC4
#define PWM_SERVO_12_OC_BIT (1<<3)
#else
#define PWM_SERVO_12_OC_BIT 0
#endif


#if USE_PWM13
#define PWM_SERVO_13 12
#define PWM_SERVO_13_TIMER TIM5
#define PWM_SERVO_13_GPIO GPIO_BANK_TIM5_CH1
#define PWM_SERVO_13_PIN GPIO_TIM5_CH1
#define PWM_SERVO_13_AF 0
#define PWM_SERVO_13_OC TIM_OC1
#define PWM_SERVO_13_OC_BIT (1<<0)
#else
#define PWM_SERVO_13_OC_BIT 0
#endif

#if USE_PWM14
#define PWM_SERVO_14 13
#define PWM_SERVO_14_TIMER TIM5
#define PWM_SERVO_14_GPIO GPIO_BANK_TIM5_CH2
#define PWM_SERVO_14_PIN GPIO_TIM5_CH2
#define PWM_SERVO_14_AF 0
#define PWM_SERVO_14_OC TIM_OC2
#define PWM_SERVO_14_OC_BIT (1<<1)
#else
#define PWM_SERVO_14_OC_BIT 0
#endif

#if USE_PWM15
#define PWM_SERVO_15 14
#define PWM_SERVO_15_TIMER TIM5
#define PWM_SERVO_15_GPIO GPIO_BANK_TIM5_CH3
#define PWM_SERVO_15_PIN GPIO_TIM5_CH3
#define PWM_SERVO_15_AF 0
#define PWM_SERVO_15_OC TIM_OC3
#define PWM_SERVO_15_OC_BIT (1<<2)
#else
#define PWM_SERVO_15_OC_BIT 0
#endif

#if USE_PWM16
#define PWM_SERVO_16 15
#define PWM_SERVO_16_TIMER TIM5
#define PWM_SERVO_16_GPIO GPIO_BANK_TIM5_CH4
#define PWM_SERVO_16_PIN GPIO_TIM5_CH4
#define PWM_SERVO_16_AF 0
#define PWM_SERVO_16_OC TIM_OC4
#define PWM_SERVO_16_OC_BIT (1<<3)
#else
#define PWM_SERVO_16_OC_BIT 0
#endif


/* servos 1-4 on TIM3 */
#define PWM_TIM3_CHAN_MASK (PWM_SERVO_1_OC_BIT|PWM_SERVO_2_OC_BIT|PWM_SERVO_3_OC_BIT|PWM_SERVO_4_OC_BIT)
/* servos 5-8 on TIM4 */
#define PWM_TIM4_CHAN_MASK (PWM_SERVO_5_OC_BIT|PWM_SERVO_6_OC_BIT|PWM_SERVO_7_OC_BIT|PWM_SERVO_8_OC_BIT)
/* servos 9-12 on TIM2 */
#define PWM_TIM2_CHAN_MASK (PWM_SERVO_9_OC_BIT|PWM_SERVO_10_OC_BIT|PWM_SERVO_11_OC_BIT|PWM_SERVO_12_OC_BIT)
/* servos 13-16 on TIM5 */
#define PWM_TIM5_CHAN_MASK (PWM_SERVO_13_OC_BIT|PWM_SERVO_14_OC_BIT|PWM_SERVO_15_OC_BIT|PWM_SERVO_16_OC_BIT)






#endif /* CONFIG_LISA_L_1_0_H */
